# Generated by Django 4.1.1 on 2022-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Pending order'), (3, 'cancel order')], default=2),
        ),
    ]
