# Generated by Django 4.1.1 on 2022-10-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
