# Generated by Django 4.1.1 on 2022-10-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_to_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_To_Cart',
            new_name='Cart',
        ),
    ]
