# Generated by Django 4.1.1 on 2022-10-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
