# Generated by Django 4.1.1 on 2022-10-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
