# Generated by Django 4.1.1 on 2022-10-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
