# Generated by Django 4.1.1 on 2022-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
