# Generated by Django 4.1.1 on 2022-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_created_at_cart_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
