# Generated by Django 4.1.1 on 2022-11-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(default=0.1),
        ),
    ]
