# Generated by Django 4.1.1 on 2022-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Pending order'), (3, 'cancel order')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Pending order'), (3, 'cancel order')], default=2),
        ),
    ]
