# Generated by Django 4.1.1 on 2022-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_cart_cart_status_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Pending order'), (3, 'cancel order')], default=1),
        ),
    ]
